title: Manifold Explorer
description: Beyond Accuracy — Open-set geometry & diagnostics

remote_theme: just-the-docs/just-the-docs
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      nav_exclude: true

plugins:
  - jekyll-remote-theme

baseurl: "/manifol-explorer"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

search_enabled: true

color_scheme: color



